version: "3.9"
services:
  database:
    image: postgres
    container_name: dev-db1
    restart: always
    volumes:
      - pgdata:/data/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
      - POSTGRES_HOST=localhost
volumes:
  pgdata:
    driver: local
